name: Scheduled Bot

#on:
  # schedule:
  #   # Her 15 dakikada bir çalıştır (cron tabanlı zamanlama)
  #   - cron: '*/1 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # .NET sürümünüze uygun şekilde ayarlayın

    - name: Restore dependencies
      run: dotnet restore

    - name: Run the bot
      run: dotnet run --project ./BotProject # Bot projenizin yolunu belirtin
